# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-slim


# Set the working directory inside the container
WORKDIR /app

# Copy the built Spring Boot JAR into the container
COPY target/safeplaces-0.0.1-SNAPSHOT.jar /app/safeplaces-service.jar

# Expose the port your Safe Places service runs on
EXPOSE 8082

# Run the Safe Places service
CMD ["java", "-jar", "/app/safeplaces-service.jar"]
